C- Common block croppar
      REAL CAO(5,0:MAXCROP),CSC(4,0:MAXCROP),
     &    UR(3,0:MAXCROP),UT(3,0:MAXCROP),
     &    CFACT(0:MAXCROP),SEED(0:MAXCROP),
     &    C1(0:MAXCROP),T1(0:MAXCROP),
     &    RRG(0:MAXCROP),RRX(0:MAXCROP),
     &    INC(2,0:MAXCROP),CRATE(0:MAXCROP),
     &    ANRATE(0:MAXCROP),
     &    STRAW(4,0:MAXCROP)
      INTEGER L_TSS(0:MAXCROP),IROCKS(0:MAXCROP)
      COMMON/CROPPAR/MCROP,CAO,CSC,UR,UT,CFACT,SEED,C1,T1,L_TSS,
     &    RRG,RRX,IROCKS,INC,CRATE,ANRATE,STRAW
