C- Common block soilpar
      REAL*8 BIORATE(MAXSOIL,MAXLAYER),HUMRATE(MAXSOIL,MAXLAYER),
     &  TOCARRAY(MAXSOIL,MAXLAYER),IOMARRAY(MAXSOIL,MAXLAYER)
      COMMON/SOILPAR/BIORATE,HUMRATE,TOCARRAY,IOMARRAY
